# These are supported funding model platforms

github: [fredamaral] # Replace with your GitHub username
patreon: mcpmemory
open_collective: mcp-memory
ko_fi: mcpmemory
tidelift: # npm/mcp-memory
community_bridge: # mcp-memory
liberapay: # mcpmemory
issuehunt: # your-org/mcp-memory
otechie: # mcpmemory
custom: ['https://mcpmemory.dev/sponsor', 'https://www.buymeacoffee.com/mcpmemory']

# Sponsorship Tiers (displayed on GitHub Sponsors)
# 
# 🥉 Bronze Sponsor - $10/month
# - Name in README
# - Access to sponsor Discord channel
# - Priority issue support
# 
# 🥈 Silver Sponsor - $50/month  
# - All Bronze benefits
# - Logo on website
# - Monthly office hours
# - Early access to features
# 
# 🥇 Gold Sponsor - $250/month
# - All Silver benefits
# - Logo on README
# - Dedicated support channel
# - Feature request priority
# - Quarterly strategy calls
# 
# 💎 Diamond Sponsor - $1000/month
# - All Gold benefits
# - Large logo placement
# - Custom integration support
# - Direct maintainer access
# - Advisory board participation
# 
# 🚀 Enterprise Sponsor - Custom
# - All Diamond benefits
# - SLA support
# - Custom development
# - Training sessions
# - Dedicated success manager