root = "."
tmp_dir = "tmp"

[build]
  # Binary to execute after build
  bin = "./tmp/lerian-mcp-memory-server"
  # Arguments to pass to the binary
  args_bin = ["-mode=http", "-addr=:9080"]
  # Build command
  cmd = "go build -o ./tmp/lerian-mcp-memory-server ./cmd/server"
  # Watch these directories
  include_dir = ["cmd", "internal", "pkg"]
  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Exclude these directories
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git", ".idea"]
  # Exclude specific files
  exclude_file = []
  # Exclude unchanged files
  exclude_unchanged = true
  # Follow symlinks
  follow_symlink = false
  # Build delay after file change (ms)
  delay = 1000
  # Stop running old binary before starting new one
  kill_delay = 500

[color]
  # Colorize output
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  # Show log time
  time = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true