version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
    - e2e
  concurrency: 4
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - gosec
    - misspell
    - nilnil
    - prealloc
    - unconvert
    - unparam
    - goconst
    - gocritic
    - gocyclo
    - nestif
    - whitespace