version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
    - e2e

linters:
  enable:
    # Core linters - these catch real bugs
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Important quality linters
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gosec
    - misspell
    - nilnil
    - prealloc
    - unconvert
    - unparam
    
    # Reasonable style linters
    - goconst
    - gocritic
    - gocyclo
    # - funlen
    - nestif

linters-settings:
  dupl:
    threshold: 200  # Increase threshold for duplicate detection

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  new: false
  fix: false
  exclude-rules:
    # Exclude dupl linter for builtin_patterns.go as it has intentionally similar patterns
    - path: internal/intelligence/builtin_patterns.go
      linters:
        - dupl

# severity section removed to fix compatibility issue