version: "2"

run:
  timeout: 10m
  tests: true
  go: '1.23'

linters:
  enable:
    # Core quality checks - essential for code correctness
    - govet          # Vet examines Go source code
    - ineffassign    # Detects ineffectual assignments
    - unused         # Checks for unused constants, variables, functions and types
    - copyloopvar    # Checks for pointers to enclosing loop variables
    - misspell       # Finds commonly misspelled English words in comments
    - whitespace     # Tool for detection of leading and trailing whitespace
    - nilnil         # Checks that there is no simultaneous return of nil error and nil value
    - errcheck       # Too many unchecked error issues
    - staticcheck    # Too many style/opinionated checks
    - gosec          # Security checks too strict for development
    - bodyclose      # HTTP body close checks
    - durationcheck  # Duration multiplication checks
    - contextcheck   # Too strict for existing codebase patterns
    - errorlint      # Too strict for error handling patterns
    - goconst        # Style preference, not critical
    - gocyclo        # Complexity is managed by code review
    - nestif         # Nesting is managed by code review  
    - dupl           # Code duplication is managed by code review
    - prealloc       # Performance optimization, not critical
    - unconvert      # Style preference, not critical
    - unparam        # Parameter usage is contextual
    - gocritic       # Too many opinionated checks
    - nolintlint     # Meta-linting, not critical
  
  settings:
    gocyclo:
      min-complexity: 15
    nestif:
      min-complexity: 5
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - commentedOutCode
        - ifElseChain
    staticcheck:
      checks: ["all"]
    errcheck:
      check-type-assertions: false
      check-blank: false
