# Lerian MCP Memory Server 
# Go-based MCP server providing persistent memory capabilities for AI assistants

# This compose file depends on the .env file in the root directory
# Copy .env.example to .env and configure as needed

services:
  # Qdrant Vector Database - High-performance vector search engine
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lerian-mcp-qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_HOST_PORT:-6333}:6333"  # HTTP API
      - "${QDRANT_GRPC_PORT:-6334}:6334"  # gRPC API
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__CLUSTER__ENABLED=false
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - lerian_mcp_network

  # Lerian MCP Memory Server (Go Backend)
  lerian-mcp-memory:
    image: ghcr.io/lerianstudio/lerian-mcp-memory:latest
    container_name: lerian-mcp-memory-server
    restart: unless-stopped
    depends_on:
      - qdrant
    ports:
      - "${MCP_HOST_PORT:-9080}:9080"    # MCP API port
      - "${MCP_HEALTH_PORT:-8081}:8081"  # Health check port
      - "${MCP_METRICS_PORT:-9082}:8082" # Metrics port (optional)
    env_file:
      - .env
    environment:
      # Override specific values that must be set for container networking
      - MCP_MEMORY_QDRANT_HOST=qdrant
      - MCP_MEMORY_DATA_DIR=/app/data
      - MCP_MEMORY_CONFIG_DIR=/app/config
      - MCP_MEMORY_HTTP_PORT=9080
      - MCP_MEMORY_HEALTH_PORT=8081
      - MCP_MEMORY_METRICS_PORT=8082
    volumes:
      - mcp_data:/app/data
      - mcp_logs:/app/logs
      - mcp_backups:/app/backups
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 40s
    labels:
      # Enable automatic updates via Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - lerian_mcp_network

  # Watchtower - Automatic container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: lerian-mcp-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      # Override specific Watchtower settings
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      # Don't auto-update watchtower itself
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - lerian_mcp_network

# Networks
networks:
  lerian_mcp_network:
    driver: bridge

# Volumes - CRITICAL: These contain all your memory data. NEVER DELETE!
volumes:
  # CRITICAL: Qdrant vector database - Contains all embeddings and search indices
  qdrant_data:
    driver: local
    name: mcp_memory_qdrant_vector_db_NEVER_DELETE

  # CRITICAL: MCP server data - Contains SQLite database and app data
  mcp_data:
    driver: local
    name: mcp_memory_app_data_NEVER_DELETE

  # Application logs - Safe to recreate but useful for debugging
  mcp_logs:
    driver: local
    name: mcp_memory_logs_NEVER_DELETE

  # Backup storage - Contains automated backups of your data
  mcp_backups:
    driver: local
    name: mcp_memory_backups_NEVER_DELETE