# Lerian MCP Memory Server - Development Configuration
# This file extends docker-compose.yml for local development with hot reload

# This compose file depends on the .env file in the root directory
# Copy .env.example to .env and configure as needed

services:
  # Override the lerian-mcp-memory service to build locally
  lerian-mcp-memory:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VERSION=${VERSION:-dev}
        - BUILD_TIME=${BUILD_TIME:-dev}
        - COMMIT_HASH=${COMMIT_HASH:-dev}
    image: lerian-mcp-memory:dev
    depends_on:
      - qdrant
    volumes:
      # Mount source code for development
      - ./cmd:/app/cmd:ro
      - ./internal:/app/internal:ro
      - ./pkg:/app/pkg:ro
      - ./configs:/app/configs:ro
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro
      # Use named volumes for data persistence
      - mcp_data:/app/data
      - mcp_logs:/app/logs
      - mcp_backups:/app/backups
    env_file:
      - .env
    environment:
      # Development-specific environment variables (overrides)
      - MCP_MEMORY_LOG_LEVEL=debug
      - MCP_MEMORY_DEV_MODE=true
      - CGO_ENABLED=0
      - GOOS=linux
    # Override command for development with hot reload
    command: ["air", "-c", ".air.toml"]