version: '3.8'

services:
  mcp-memory-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-memory-server
    volumes:
      # Mount source code for hot reload
      - ./cmd:/app/cmd:ro
      - ./internal:/app/internal:ro
      - ./pkg:/app/pkg:ro
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro
      # Data volumes
      - mcp_memory_data:/app/data
      - mcp_memory_logs:/app/logs
      - mcp_memory_backups:/app/backups
    ports:
      - "9080:9080"  # MCP HTTP endpoint
      - "9090:9090"  # Metrics endpoint
    environment:
      - MCP_MEMORY_LOG_LEVEL=debug
      - MCP_MEMORY_ENVIRONMENT=development
      - MCP_MEMORY_STORAGE_PROVIDER=qdrant
      - MCP_MEMORY_QDRANT_HOST=mcp-qdrant
      - MCP_MEMORY_QDRANT_PORT=6334
      - MCP_MEMORY_QDRANT_COLLECTION=claude_memory
      - MCP_MEMORY_SERVER_HOST=0.0.0.0
      - MCP_MEMORY_SERVER_PORT=9080
      - MCP_MEMORY_HEALTH_ENABLED=true
      - MCP_MEMORY_HEALTH_PORT=9080
      - MCP_MEMORY_METRICS_ENABLED=true
      - MCP_MEMORY_METRICS_PORT=9090
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      - mcp-qdrant
    networks:
      - mcp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-qdrant:
    image: qdrant/qdrant:latest
    container_name: mcp-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__CLUSTER__ENABLED=false
      - QDRANT__LOG_LEVEL=DEBUG
    networks:
      - mcp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mcp_memory_data:
  mcp_memory_logs:
  mcp_memory_backups:
  qdrant_data:

networks:
  mcp_network:
    driver: bridge