version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: claude-memory-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Add a simple web UI for Chroma (development only)
  chroma-ui:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: claude-memory-chroma-ui
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_HTTP_PORT=8000
    depends_on:
      - chroma
    profiles:
      - ui