# Alerting rules for Lerian MCP Memory Server
groups:
  - name: mcp-memory-server
    rules:
      # Service availability alerts
      - alert: MCPMemoryServerDown
        expr: up{job="lerian-mcp-memory-server"} == 0
        for: 1m
        labels:
          severity: critical
          service: mcp-memory-server
        annotations:
          summary: "MCP Memory Server is down"
          description: "The MCP Memory Server has been down for more than 1 minute."

      - alert: MCPMemoryServerHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="lerian-mcp-memory-server"}[5m])) > 1
        for: 2m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High latency on MCP Memory Server"
          description: "95th percentile latency is {{ $value }} seconds for {{ $labels.instance }}."

      # Memory and resource alerts
      - alert: MCPMemoryServerHighMemoryUsage
        expr: (go_memstats_alloc_bytes{job="lerian-mcp-memory-server"} / go_memstats_sys_bytes{job="lerian-mcp-memory-server"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High memory usage on MCP Memory Server"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}."

      - alert: MCPMemoryServerHighGoroutines
        expr: go_goroutines{job="lerian-mcp-memory-server"} > 1000
        for: 5m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High number of goroutines"
          description: "Number of goroutines is {{ $value }} on {{ $labels.instance }}."

      # Error rate alerts
      - alert: MCPMemoryServerHighErrorRate
        expr: rate(http_requests_total{job="lerian-mcp-memory-server",status=~"5.."}[5m]) / rate(http_requests_total{job="lerian-mcp-memory-server"}[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
          service: mcp-memory-server
        annotations:
          summary: "High error rate on MCP Memory Server"
          description: "Error rate is {{ $value }}% on {{ $labels.instance }}."

      # Database connection alerts
      - alert: MCPMemoryServerDatabaseConnectionIssues
        expr: mcp_memory_database_connections_active{job="lerian-mcp-memory-server"} == 0
        for: 1m
        labels:
          severity: critical
          service: mcp-memory-server
        annotations:
          summary: "Database connection issues"
          description: "No active database connections on {{ $labels.instance }}."

  - name: qdrant-vector-db
    rules:
      # Qdrant availability
      - alert: QdrantDown
        expr: up{job="qdrant"} == 0
        for: 1m
        labels:
          severity: critical
          service: qdrant
        annotations:
          summary: "Qdrant vector database is down"
          description: "Qdrant has been down for more than 1 minute."

      # Qdrant performance
      - alert: QdrantHighSearchLatency
        expr: qdrant_search_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
          service: qdrant
        annotations:
          summary: "High search latency in Qdrant"
          description: "95th percentile search latency is {{ $value }} seconds."

      # Qdrant storage
      - alert: QdrantHighDiskUsage
        expr: qdrant_disk_usage_ratio > 0.85
        for: 5m
        labels:
          severity: warning
          service: qdrant
        annotations:
          summary: "High disk usage in Qdrant"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

  - name: memory-operations
    rules:
      # Memory operation specific alerts
      - alert: MCPMemoryHighChunkCreationFailures
        expr: rate(mcp_memory_chunk_creation_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High chunk creation failure rate"
          description: "Chunk creation failure rate is {{ $value }} per second."

      - alert: MCPMemoryHighSearchFailures
        expr: rate(mcp_memory_search_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High search failure rate"
          description: "Search failure rate is {{ $value }} per second."

      - alert: MCPMemoryLowSearchRelevance
        expr: avg(mcp_memory_search_relevance_score) < 0.5
        for: 10m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "Low search relevance scores"
          description: "Average search relevance score is {{ $value }}."

  - name: ai-service
    rules:
      # AI service integration alerts
      - alert: MCPMemoryHighOpenAIErrors
        expr: rate(mcp_memory_openai_api_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "High OpenAI API error rate"
          description: "OpenAI API error rate is {{ $value }} per second."

      - alert: MCPMemoryOpenAIRateLimited
        expr: increase(mcp_memory_openai_rate_limited_total[1h]) > 10
        for: 0m
        labels:
          severity: warning
          service: mcp-memory-server
        annotations:
          summary: "OpenAI API rate limiting detected"
          description: "{{ $value }} rate limit hits in the last hour."