# Prometheus configuration for Lerian MCP Memory Server monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    service: "lerian-mcp-memory"
    environment: "production"

# Rule files for alerting
rule_files:
  - "alerts/*.yml"

# Scrape configurations for different targets
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Lerian MCP Memory Server metrics
  - job_name: 'lerian-mcp-memory-server'
    static_configs:
      - targets: ['lerian-mcp-memory:8082']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Qdrant vector database metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # PostgreSQL exporter (if using monitoring profile)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Performance tuning
runtime:
  gomaxprocs: 2