# Claude Vector Memory MCP Server - Development Configuration

server:
  host: "localhost"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

health:
  enabled: true
  port: 8081
  path: "/health"

metrics:
  enabled: true
  port: 8082
  path: "/metrics"
  interval: 15s

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  structured: false

storage:
  type: "sqlite"
  sqlite:
    path: "./data/memory_dev.db"
    max_connections: 10
    connection_max_lifetime: 300s

vector:
  engine: "faiss"
  dimension: 1536
  persist_path: "./data/vectors_dev"
  cache_size: 1000

memory:
  conversation_history_limit: 100
  max_memory_entries: 10000
  cleanup_interval: 30m

intelligence:
  pattern_recognition:
    enabled: true
    min_pattern_frequency: 2
  knowledge_graph:
    enabled: true
    max_entities: 5000
  context_suggestion:
    enabled: true
    max_suggestions: 5
  learning:
    enabled: true

caching:
  memory:
    enabled: true
    size: 100
    ttl: 10m

security:
  encryption:
    enabled: false
  access_control:
    enabled: false
  rate_limiting:
    enabled: false

backup:
  enabled: false

monitoring:
  enabled: false

development:
  debug: true
  profiling: true
  cors:
    enabled: true
    allowed_origins: ["*"]