# Claude Vector Memory MCP Server - Development Configuration

server:
  host: "0.0.0.0"
  port: 9080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

health:
  enabled: true
  port: 9080
  path: "/health"

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  interval: 15s

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  structured: false

storage:
  type: "qdrant"
  qdrant:
    host: "mcp-qdrant"
    port: 6334
    api_key: ""
    collection_name: "claude_memory"
    use_tls: false

memory:
  conversation_history_limit: 100
  max_memory_entries: 10000
  cleanup_interval: 30m

intelligence:
  pattern_recognition:
    enabled: true
    min_pattern_frequency: 2
  knowledge_graph:
    enabled: true
    max_entities: 5000
  context_suggestion:
    enabled: true
    max_suggestions: 5
  learning:
    enabled: true

caching:
  memory:
    enabled: true
    size: 100
    ttl: 10m

security:
  encryption:
    enabled: false
  access_control:
    enabled: false
  rate_limiting:
    enabled: false

backup:
  enabled: false

monitoring:
  enabled: false

development:
  debug: true
  profiling: true
  cors:
    enabled: true
    allowed_origins: ["*"]