# Prometheus configuration for MCP Memory Server monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # MCP Memory Server metrics
  - job_name: 'mcp-memory-server'
    static_configs:
      - targets: ['mcp-memory-server:8082']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Health checks
  - job_name: 'mcp-memory-health'
    static_configs:
      - targets: ['mcp-memory-server:8081']
    scrape_interval: 30s
    metrics_path: /health
    scheme: http

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker metrics (if using docker daemon metrics)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s