# Grafana datasource configuration for Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQuerying: false
      exemplarTraceIdDestinations: []
    secureJsonData: {}
    version: 1
    editable: false

  - name: Qdrant-Metrics
    type: prometheus
    access: proxy
    url: http://qdrant:6333
    jsonData:
      httpMethod: GET
      manageAlerts: false
      prometheusType: Prometheus
    secureJsonData: {}
    version: 1
    editable: false